name: quality_education_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_slidable: ^0.6.0
  flutter_carousel_slider: ^1.1.0
  intl: ^0.18.1
  barcode: ^2.2.3
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2 
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Mukta
      fonts:
        - asset: fonts/Mukta-Bold.ttf
        - asset: fonts/Mukta-ExtraBold.ttf
        - asset: fonts/Mukta-ExtraLight.ttf
        - asset: fonts/Mukta-Light.ttf
        - asset: fonts/Mukta-Medium.ttf
        - asset: fonts/Mukta-Regular.ttf
        - asset: fonts/Mukta-SemiBold.ttf

  assets:
    - assets/app_logo.png
    - assets/get_started_component_1.png
    - assets/get_started_image.png
    - assets/onboarding_1.png
    - assets/onboarding_2.png
    - assets/onboarding_3.png
    - assets/facebook_logo.png
    - assets/google_logo.png
    - assets/avatar_logo.jpg
    - assets/carousel_image_1.jpg
    - assets/carousel_image_2.jpg
    - assets/carousel_image_3.jpg
    - assets/carousel_image_4.jpg
    - assets/math_logo_primary.png
    - assets/biology_logo_primary.png
    - assets/physics_logo_primary.png
    - assets/chemistry_logo_primary.png
    - assets/economy_logo_primary.png
    - assets/geography_logo_primary.png
    - assets/math_logo_secondary.png
    - assets/biology_logo_secondary.png
    - assets/physics_logo_secondary.png
    - assets/chemistry_logo_secondary.png
    - assets/economy_logo_secondary.png
    - assets/geography_logo_secondary.png
    - assets/history_logo_secondary.png
    - assets/math_course_1.jpg
    - assets/physics_course_1.jpg
    - assets/chemistry_course_1.jpg
    - assets/biology_course_1.jpg
    - assets/economy_course_1.webp
    - assets/ovo_logo.png
    - assets/gopay_logo.png
    - assets/dana_logo.png
    - assets/shopee_pay_logo.png
    - assets/credit_card_logo.png
    - assets/mandiri_logo.png
    - assets/bca_logo.png
    - assets/bri_logo.png
    - assets/bni_logo.png
    - assets/news_image_1.jpg
    - assets/news_image_2.jpg
    - assets/news_image_3.jpg
    - assets/news_image_4.jpg
    - assets/learning_banner.png
    - assets/exercise_banner.png
    - assets/challenge_banner.png 